
version: "3.9"

services:
  db:
    image: "spst_api_container"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD:  ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  server:
    build: .
    ports:
      - "8111:8111"
    environment:
      DATABASE_URL: ${DATABASE_URL}